version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:14.2-bullseye

    build:
      context: .
    env_file: .env
    environment:
      POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256'
      POSTGRES_HOST_AUTH_METHOD: 'scram-sha-256'
      POSTGRES_DB: 'vkwork'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: ${POSTGRES_USER}
      # You can use whatever password you like
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    expose:
      - '5432'
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
